include theos/makefiles/common.mk
BUNDLE_NAME = SLDockPlugin
SLDockPlugin_FILES = SLDockPlugin.mm
SLDockPlugin_INSTALL_PATH = /Library/SwitcherLoader/Plugins
SLDockPlugin_FRAMEWORKS = UIKit
include $(THEOS_MAKE_PATH)/bundle.mk

